# Generated by Django 6.0.2 on 2026-03-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DismissalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Причина увольнения')),
            ],
            options={
                'verbose_name': 'Причина увольнения',
                'verbose_name_plural': 'Причины увольнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Категория работника')),
            ],
            options={
                'verbose_name': 'Категория работника',
                'verbose_name_plural': 'Категории работников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название производства')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Номер цеха')),
                ('name', models.CharField(blank=True, help_text='Полное название цеха (необязательное поле)', max_length=255, verbose_name='Название цеха')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='core.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('employee_number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Табельный номер')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Даат обновления записи')),
                ('dismissal_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissal_employees', to='core.dismissalreason', verbose_name='Причина увольнения')),
                ('employee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_employees', to='core.employeecategory', verbose_name='Категория работника')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_employees', to='core.position', verbose_name='Должность')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_employees', to='core.production', verbose_name='Производство')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_employees', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['dismissal_date'], name='core_employ_dismiss_d0006b_idx')],
            },
        ),
    ]
