# Generated by Django 6.0.3 on 2026-04-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setup_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Источник приема')),
            ],
            options={
                'verbose_name': 'Источник приема',
                'verbose_name_plural': 'Источники приема',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Полное ФИО: Фамилия Имя Отчество', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hire_source_employees', to='core.hiresource', verbose_name='Источник приема'),
        ),
    ]
