# Generated by Django 6.0.3 on 2026-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hiresource_alter_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Разряд'),
        ),
    ]
