# Generated by Django 6.0.3 on 2026-04-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Причина увольнения')),
            ],
            options={
                'verbose_name': 'Причина увольнения',
                'verbose_name_plural': 'Причины увольнения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_grades', to='core.employeegrades', verbose_name='Разряд'),
        ),
    ]
