# Generated by Django 6.0.3 on 2026-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeegrades_alter_employee_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeegrades',
            options={'ordering': ['name'], 'verbose_name': 'Разряд', 'verbose_name_plural': 'Разряды'},
        ),
        migrations.AlterField(
            model_name='employeegrades',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Разряд'),
        ),
    ]
