# Generated by Django 6.0.3 on 2026-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employeegrades_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='number',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Номер цеха'),
        ),
    ]
