# Generated by Django 6.0.3 on 2026-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_workshop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='number',
            field=models.CharField(db_index=True, unique=True, verbose_name='Номер цеха'),
        ),
    ]
