# Generated by Django 6.0.3 on 2026-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_workshop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='-', max_length=8, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reg_address',
            field=models.CharField(blank=True, null=True, verbose_name='Адрес регистрации'),
        ),
    ]
