# Generated by Django 6.0.3 on 2026-04-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_gender_employee_reg_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, verbose_name='Номер приказа')),
                ('transfer_date', models.DateField(verbose_name='Дата рождения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_employee', to='core.employee', verbose_name='Переводы')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_grade', to='core.employeegrades', verbose_name='С разряда')),
                ('from_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_position', to='core.position', verbose_name='С должности')),
                ('from_workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_workshop', to='core.workshop', verbose_name='Из цеха')),
                ('to_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_grade', to='core.employeegrades', verbose_name='На разряд')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_position', to='core.position', verbose_name='На должность')),
                ('to_workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_workshop', to='core.workshop', verbose_name='В цех')),
            ],
        ),
    ]
