# Generated by Django 6.0.3 on 2026-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employeetransfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetransfers',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AddConstraint(
            model_name='employeetransfers',
            constraint=models.UniqueConstraint(fields=('employee', 'order_number', 'transfer_date'), name='unique_employee_transfers'),
        ),
    ]
