# Generated by Django 6.0.3 on 2026-04-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employeetransfers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransfers',
            name='from_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_grade', to='core.employeegrades', verbose_name='С разряда'),
        ),
        migrations.AlterField(
            model_name='employeetransfers',
            name='to_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_grade', to='core.employeegrades', verbose_name='На разряд'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Полное ФИО: Иванов Иван Иванович', max_length=255, verbose_name='ФИО'),
        ),
    ]
