# Generated by Django 6.0.3 on 2026-04-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employeetransfers_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransfers',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_employee', to='core.employee', verbose_name='Переводы'),
        ),
        migrations.AlterField(
            model_name='employeetransfers',
            name='from_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_position', to='core.position', verbose_name='С должности'),
        ),
        migrations.AlterField(
            model_name='employeetransfers',
            name='from_workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_workshop', to='core.workshop', verbose_name='Из цеха'),
        ),
        migrations.AlterField(
            model_name='employeetransfers',
            name='to_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_position', to='core.position', verbose_name='На должность'),
        ),
        migrations.AlterField(
            model_name='employeetransfers',
            name='to_workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_workshop', to='core.workshop', verbose_name='В цех'),
        ),
    ]
