# Generated by Django 6.0.3 on 2026-04-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_employeetransfers_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransfers',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_employee', to='core.employee', verbose_name='Переводы'),
        ),
    ]
