# Generated by Django 6.0.3 on 2026-04-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_employeetransfers_from_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransfers',
            name='from_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_category', to='core.employeecategory', verbose_name='Категория до перевода'),
        ),
        migrations.AddField(
            model_name='employeetransfers',
            name='to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_category', to='core.employeecategory', verbose_name='Категория после перевода'),
        ),
    ]
