# Generated by Django 6.0.3 on 2026-05-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_employeetransfers_from_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Категория приема')),
            ],
            options={
                'verbose_name': 'Категория приема',
                'verbose_name_plural': 'Категории приема',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissal_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissal_employees', to='core.dismissalreason', verbose_name='Причина увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_employees', to='core.employeecategory', verbose_name='Категория работника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_grades', to='core.employeegrades', verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_source_employees', to='core.hiresource', verbose_name='Источник приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_employees', to='core.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_employees', to='core.production', verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_employees', to='core.workshop', verbose_name='Цех'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_category', to='core.hirecategory', verbose_name='Категория приема'),
        ),
    ]
