# Generated by Django 6.0.3 on 2026-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_hirecategory_alter_employee_dismissal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dismissal_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения(факт)'),
        ),
    ]
