# Generated by Django 6.0.3 on 2026-06-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_dismissal_date_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_order_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер приказа о приёме'),
        ),
    ]
