# Generated by Django 6.0.3 on 2026-06-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_employee_hire_order_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_date', models.DateField(verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(verbose_name='Дата увольнения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_id', to='core.employee', verbose_name='id Работника')),
            ],
            options={
                'verbose_name': 'Приемы/увольнения',
                'verbose_name_plural': 'Прием/увольнение',
            },
        ),
    ]
