# Generated by Django 6.0.3 on 2026-06-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_employeehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='dismissal_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_dismissal_employees', to='core.dismissalreason', verbose_name='Причина увольнения'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='hire_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_hire_source_employees', to='core.hiresource', verbose_name='Источник приема'),
        ),
    ]
