# Generated by Django 6.0.3 on 2026-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_employeehistory_dismissal_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
