# Generated by Django 6.0.3 on 2026-06-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_employeehistory_dismissal_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeehistory',
            constraint=models.UniqueConstraint(fields=('employee', 'hiring_date', 'dismissal_date', 'dismissal_reason', 'hire_source'), name='unique_employee_history'),
        ),
    ]
