# Generated by Django 6.0.3 on 2026-06-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_employeehistory_unique_employee_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='hire_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_category_history', to='core.hirecategory', verbose_name='Категория приема'),
        ),
    ]
