# Generated by Django 6.0.3 on 2026-06-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_employeehistory_hire_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeehistory',
            name='unique_employee_history',
        ),
        migrations.AddConstraint(
            model_name='employeehistory',
            constraint=models.UniqueConstraint(fields=('employee', 'hiring_date', 'dismissal_date', 'dismissal_reason', 'hire_source', 'hire_category'), name='unique_employee_history'),
        ),
    ]
