# Generated by Django 6.0.3 on 2026-06-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_employeehistory_unique_employee_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField()),
                ('prod', models.CharField()),
                ('f_3', models.IntegerField()),
                ('f_4', models.IntegerField()),
                ('f_5', models.FloatField()),
                ('f_6', models.IntegerField()),
                ('f_7', models.IntegerField()),
                ('f_8', models.FloatField()),
                ('f_9', models.FloatField()),
                ('f_10', models.IntegerField()),
                ('f_11', models.IntegerField()),
                ('f_12', models.FloatField()),
                ('f_13', models.FloatField()),
                ('f_14', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_history', to='core.employee', verbose_name='id Работника'),
        ),
    ]
