# Generated by Django 6.0.3 on 2026-06-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reporttable_alter_employeehistory_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='table_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
