# Generated by Django 6.0.3 on 2026-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_reporttable_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='dep',
            field=models.CharField(null=True),
        ),
    ]
