# Generated by Django 6.0.3 on 2026-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_reporttable_dep'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reporttable',
            constraint=models.UniqueConstraint(fields=('dep', 'prod', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10', 'f_11', 'f_12', 'f_13', 'f_14', 'table_date'), name='unique_table_report'),
        ),
    ]
